# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomerium < Formula
  desc ""
  homepage ""
  version "0.22.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomerium/pomerium/releases/download/v0.22.0/pomerium-darwin-amd64.tar.gz"
      sha256 "f4f2b38eeb32b5c7ede0469fed1d3e699b5e897af3a6167e519e738865587127"

      def install
        bin.install "pomerium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomerium/pomerium/releases/download/v0.22.0/pomerium-linux-arm64.tar.gz"
      sha256 "d0a68ca19e06ea18ba1b9355f372fdac176fe3c16ca6c987caaf6c3498fb9a38"

      def install
        bin.install "pomerium"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pomerium/pomerium/releases/download/v0.22.0/pomerium-linux-amd64.tar.gz"
      sha256 "0f97690a2f1df539e94fc6dc831a36b08ab3cdd2024ba9982350fb6ccea69aef"

      def install
        bin.install "pomerium"
      end
    end
  end
end
