# This file was generated by GoReleaser. DO NOT EDIT.
class PomeriumCli < Formula
  desc ""
  homepage ""
  version "0.10.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pomerium/pomerium/releases/download/v0.10.0/pomerium-cli-darwin-amd64.tar.gz"
    sha256 "f982f0009b6b9934b219d5251dc21861af40e1d57d7cc977eabb344f9c246aaf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pomerium/pomerium/releases/download/v0.10.0/pomerium-cli-linux-amd64.tar.gz"
      sha256 "3282b5a59030534890a3c829b5048c0aadbbea7e0c727bd8bde7fae0f7eaaea6"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pomerium/pomerium/releases/download/v0.10.0/pomerium-cli-linux-arm64.tar.gz"
        sha256 "8ad64b63c8776103a144d4cde86939e25047bc4df26341a57d02f1ba3c8aaee0"
      else
        url "https://github.com/pomerium/pomerium/releases/download/v0.10.0/pomerium-cli-linux-armv6.tar.gz"
        sha256 "7541e521dfee3518eb1b3eea540af47dc33d64a900663e5cb4e07c24194fa602"
      end
    end
  end

  def install
    bin.install "pomerium-cli"
  end
end
