# This file was generated by GoReleaser. DO NOT EDIT.
class Pomerium < Formula
  desc ""
  homepage ""
  version "0.11.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pomerium/pomerium/releases/download/v0.11.1/pomerium-darwin-amd64.tar.gz"
    sha256 "a0652bd8a2af788e46103f2c6d2271eaf990b76e33f88d12b9b43ac18ba5f004"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pomerium/pomerium/releases/download/v0.11.1/pomerium-linux-amd64.tar.gz"
    sha256 "5986cc3d3d7d1b3a0dddfe8804911ed6b2fc8fef1d42febc024cdc93c944afa2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/pomerium/pomerium/releases/download/v0.11.1/pomerium-linux-arm64.tar.gz"
    sha256 "e141b61de08a4acb9f7d0527deb872dd1296c373fd3a4bb6b9b6894b7357cc6f"
  end

  def install
    bin.install "pomerium"
  end
end
