# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomerium < Formula
  desc ""
  homepage ""
  version "0.29.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pomerium/pomerium/releases/download/v0.29.2/pomerium-darwin-amd64.tar.gz"
      sha256 "acbc45471a89971344f3ccfacb94deca284e9a218934819a0a4b1cc31474c426"

      def install
        bin.install "pomerium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pomerium/pomerium/releases/download/v0.29.2/pomerium-linux-amd64.tar.gz"
      sha256 "4bff483629832aabbe917605a574b11f54011816e2d8429a1554a442d43ebe19"

      def install
        bin.install "pomerium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pomerium/pomerium/releases/download/v0.29.2/pomerium-linux-arm64.tar.gz"
      sha256 "7d16a6d9da6d7f901f3d84919db504c572a12bc6998da3f9eeb770869422ab60"

      def install
        bin.install "pomerium"
      end
    end
  end
end
