# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PomeriumCli < Formula
  desc ""
  homepage ""
  version "0.13.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pomerium/pomerium/releases/download/v0.13.4/pomerium-cli-darwin-amd64.tar.gz"
    sha256 "7d839c498f15d8c89477cdea57f0ae9a57374261c1b36e205501aa0a22057ae2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pomerium/pomerium/releases/download/v0.13.4/pomerium-cli-linux-amd64.tar.gz"
    sha256 "7910875ce7ca3c4ad7690f479252048c9f2488c84038df70a36fc0176b92948b"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/pomerium/pomerium/releases/download/v0.13.4/pomerium-cli-linux-armv6.tar.gz"
    sha256 "2c5335cde39d71f3356f230a18928affb69f189aad65f3de018e42a7f2d62e0b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/pomerium/pomerium/releases/download/v0.13.4/pomerium-cli-linux-arm64.tar.gz"
    sha256 "30f73825423ed7689bdefbf433f2b0130ac48d95891f0a234291f1283840550b"
  end

  def install
    bin.install "pomerium-cli"
  end
end
