#!/usr/bin/env bash
set -euxo pipefail

_version=${VERSION?'VERSION is required'}

_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
_darwin_amd64_url="https://github.com/pomerium/cli/releases/download/v${_version}/pomerium-cli-darwin-amd64.tar.gz"
_darwin_arm64_url="https://github.com/pomerium/cli/releases/download/v${_version}/pomerium-cli-darwin-arm64.tar.gz"
_linux_armv6_url="https://github.com/pomerium/cli/releases/download/v${_version}/pomerium-cli-linux-armv6.tar.gz"
_linux_arm64_url="https://github.com/pomerium/cli/releases/download/v${_version}/pomerium-cli-linux-arm64.tar.gz"
_linux_amd64_url="https://github.com/pomerium/cli/releases/download/v${_version}/pomerium-cli-linux-amd64.tar.gz"

_darwin_amd64_sha256="$(curl -fL "$_darwin_amd64_url" | shasum -a 256 | cut -d' ' -f1)"
_darwin_arm64_sha256="$(curl -fL "$_darwin_arm64_url" | shasum -a 256 | cut -d' ' -f1)"
_linux_armv6_sha256="$(curl -fL "$_linux_armv6_url" | shasum -a 256 | cut -d' ' -f1)"
_linux_arm64_sha256="$(curl -fL "$_linux_arm64_url" | shasum -a 256 | cut -d' ' -f1)"
_linux_amd64_sha256="$(curl -fL "$_linux_amd64_url" | shasum -a 256 | cut -d' ' -f1)"

cat <<EOF > "${_dir}/../Formula/pomerium-cli.rb"
class PomeriumCli < Formula
  desc ""
  homepage "https://www.pomerium.com"
  version "$_version"

  on_macos do
    if Hardware::CPU.intel?
      url "$_darwin_amd64_url"
      sha256 "$_darwin_amd64_sha256"

      def install
        bin.install "pomerium-cli"
      end
    end
    if Hardware::CPU.arm?
      url "$_darwin_arm64_url"
      sha256 "$_darwin_arm64_sha256"

      def install
        bin.install "pomerium-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "$_linux_armv6_url"
      sha256 "$_linux_armv6_sha256"

      def install
        bin.install "pomerium-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "$_linux_arm64_url"
      sha256 "$_linux_arm64_sha256"

      def install
        bin.install "pomerium-cli"
      end
    end
    if Hardware::CPU.intel?
      url "$_linux_amd64_url"
      sha256 "$_linux_amd64_sha256"

      def install
        bin.install "pomerium-cli"
      end
    end
  end
end
EOF
